api_platform:
    # Enable the Swagger documentation and export.
    enable_swagger: true
    # Enable Swagger UI.
    enable_swagger_ui: false
    # Enable ReDoc.
    enable_re_doc: true
    # Enable the entrypoint.
    enable_entrypoint: true
    # Enable the docs.
    enable_docs: true
    # Enable the data collector and the WebProfilerBundle integration.
    enable_profiler: false