#index:
#    path: /
#    controller: App\Controller\DefaultController::index

security:
    resource: '@CoralMediaSecurityBundle/Resources/config/routes.yaml'
web_desktop:
    resource: '@CoralMediaWebDesktopBundle/Resources/config/routes.yaml'